//
// Created by rainman on 2024/1/18.
//

#ifndef MULTI_THREADS_HASHTABLE_KVSTORE_UNIT_TEST_LRU_BUFFER_POOL_H
#define MULTI_THREADS_HASHTABLE_KVSTORE_UNIT_TEST_LRU_BUFFER_POOL_H

void lru_buffer_pool_run_all_testcases();

#endif //MULTI_THREADS_HASHTABLE_KVSTORE_UNIT_TEST_LRU_BUFFER_POOL_H
